services:
  astrochat:
    build: .
    container_name: astrochat
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: >
      sh -c "
      echo 'Instalando dependencias...' &&
      npm install &&
      echo 'Eliminando base de datos existente...' &&
      npm run migrate:down &&
      echo 'Creando base de datos...' &&
      npm run migrate:up &&
      echo 'Ejecutando seeders...' &&
      npx ts-node src/seeders/profile.seeder.ts &&
      echo 'Iniciando la aplicación...' &&
      npm run start:dev
      "
    environment:
      - NODE_ENV=development
      - RUNNING_IN_DOCKER=true
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
